import {
  Binary,
  BookOpen,
  Boxes,
  Brain,
  BrainCircuit,
  Briefcase,
  ChevronDown,
  ChevronRight,
  Cloud,
  Code2,
  Cpu,
  Database,
  Globe,
  HardDrive,
  LayoutGrid,
  Monitor,
  Network,
  Server,
  Shield,
  Sigma,
} from "lucide-react";

export const subjectCourses = [
  {
    name: "Structured Programming & C/C++",
    slug: "structured-programming-c-cpp",
    icon: Code2,
    desc: "Procedural Logic, Pointers, Memory Management, C & C++ Fundamentals",
  },
  {
    name: "Object-Oriented Programming (Java/C#)",
    slug: "object-oriented-programming",
    icon: Boxes,
    desc: "Classes, Objects, Inheritance, Polymorphism, Abstraction & Design Patterns",
  },
  {
    name: "Data Structures & Algorithms",
    slug: "dsa",
    icon: Binary,
    desc: "Arrays, Trees, Graphs, Sorting, Searching & Time-Space Complexity",
  },
  {
    name: "Discrete Mathematics",
    slug: "discrete-mathematics",
    icon: Sigma,
    desc: "Set Theory, Propositional Logic, Graph Theory & Combinatorics",
  },
  {
    name: "Digital Logic Design",
    slug: "digital-logic-design",
    icon: Cpu,
    desc: "Boolean Algebra, Logic Gates, Combinational & Sequential Circuits",
  },
  {
    name: "Database Management Systems",
    slug: "database-management-systems",
    icon: Database,
    desc: "SQL, Relational Databases, Normalization, Indexing & Transactions",
  },
  {
    name: "Computer Architecture & Organization",
    slug: "computer-architecture-organization",
    icon: HardDrive,
    desc: "CPU Design, Instruction Set Architecture, Memory Hierarchy & Pipelining",
  },
  {
    name: "Operating Systems",
    slug: "operating-systems",
    icon: Monitor,
    desc: "Process Scheduling, Concurrency, Memory Management & File Systems",
  },
  {
    name: "Computer Networks",
    slug: "computer-networks",
    icon: Network,
    desc: "OSI Model, TCP/IP, Routing, Switching & Network Protocols",
  },
  {
    name: "Software & Web Engineering",
    slug: "software-web-engineering",
    icon: Globe,
    desc: "SDLC, Web Frameworks, System Modeling, Agile & Software Architecture",
  },
  {
    name: "Cybersecurity & IT Service Management",
    slug: "cybersecurity-it-management",
    icon: Shield,
    desc: "Cryptography, Network Security, Threat Analysis & ITIL Frameworks",
  },
  {
    name: "Artificial Intelligence & Neural Networks",
    slug: "ai-neural-networks",
    icon: BrainCircuit,
    desc: "Machine Learning, Deep Learning, Search Algorithms & Neural Architectures",
  },
];
 export const htmlTags = [
    { label: 'html', open: '<html>\n', close: '\n</html>' },
    { label: 'head', open: '<head>\n', close: '\n</head>' },
    { label: 'title', open: '<title>', close: '</title>' },
    { label: 'meta desc', open: '<meta name="description" content="">', close: '' },
    { label: 'link canon', open: '<link rel="canonical" href="">', close: '' },
    { label: 'body', open: '<body>\n', close: '\n</body>' },
    { label: 'header', open: '<header>\n', close: '\n</header>' },
    { label: 'nav', open: '<nav>\n', close: '\n</nav>' },
    { label: 'main', open: '<main>\n', close: '\n</main>' },
    { label: 'article', open: '<article>\n', close: '\n</article>' },
    { label: 'section', open: '<section>\n', close: '\n</section>' },
    { label: 'h1', open: '<h1>', close: '</h1>' },
    { label: 'h2', open: '<h2>', close: '</h2>' },
    { label: 'h3', open: '<h3>', close: '</h3>' },
    { label: 'p', open: '<p>', close: '</p>' },
    { label: 'strong', open: '<strong>', close: '</strong>' },
    { label: 'em', open: '<em>', close: '</em>' },
    { label: 'ul', open: '<ul>\n  ', close: '\n</ul>' },
    { label: 'ol', open: '<ol>\n  ', close: '\n</ol>' },
    { label: 'li', open: '<li>', close: '</li>' },
    { label: 'img', open: '<img src="" alt="">', close: '' },
    { label: 'figure', open: '<figure>\n  ', close: '\n</figure>' },
    { label: 'figcaption', open: '<figcaption>', close: '</figcaption>' },
    { label: 'a', open: '<a href="">', close: '</a>' },
    { label: 'table', open: '<table>\n  <tr>\n    <td></td>\n  </tr>\n</table>', close: '' },
    { label: 'blockquote', open: '<blockquote>\n  ', close: '\n</blockquote>' },
    { label: 'details', open: '<details>\n  <summary>Title</summary>\n  ', close: '\n</details>' },
    { label: 'time', open: '<time datetime="">', close: '</time>' },
    { label: 'footer', open: '<footer>\n', close: '\n</footer>' },
  ];