import {
  Code2,
  Server,
  Database,
  Globe,
  Shield,
  Network,
  Boxes,
  Cloud,
  Brain,
  Briefcase,
  ChevronDown,
  BookOpen,
  LayoutGrid,
  ChevronRight,
} from "lucide-react";
export const subjectCourses = [
  {
    name: "JavaScript & TypeScript",
    slug: "javascript-typescript",
    icon: Code2,
    desc: "Modern JavaScript, ES6+, TypeScript & Best Practices",
  },
  {
    name: "Frontend Engineering",
    slug: "frontend-engineering",
    icon: Globe,
    desc: "HTML, CSS, React, Next.js & UI Engineering",
  },
  {
    name: "Backend Engineering",
    slug: "backend-engineering",
    icon: Server,
    desc: "Node.js, Express.js, NestJS & APIs",
  },
  {
    name: "Databases",
    slug: "databases",
    icon: Database,
    desc: "SQL, PostgreSQL, MongoDB, Prisma & Redis",
  },
  {
    name: "System Design",
    slug: "system-design",
    icon: Network,
    desc: "Scalable Architecture, Microservices & Distributed Systems",
  },
  {
    name: "DevOps & Cloud",
    slug: "devops-cloud",
    icon: Cloud,
    desc: "Docker, CI/CD, AWS, Linux & Deployment",
  },
  {
    name: "Security & Authentication",
    slug: "security",
    icon: Shield,
    desc: "JWT, OAuth, RBAC, OWASP & Secure APIs",
  },
  {
    name: "DSA & Problem Solving",
    slug: "dsa-problem-solving",
    icon: Brain,
    desc: "Data Structures, Algorithms & Coding Interviews",
  },
  {
    name: "Tools & Engineering",
    slug: "tools-engineering",
    icon: Boxes,
    desc: "Git, GitHub, Testing, Debugging & Developer Tools",
  },
  {
    name: "Interview Preparation",
    slug: "interview-preparation",
    icon: Briefcase,
    desc: "Behavioral, System Design & Technical Interview Prep",
  },
];
 export const htmlTags = [
    { label: 'html', open: '<html>\n', close: '\n</html>' },
    { label: 'head', open: '<head>\n', close: '\n</head>' },
    { label: 'title', open: '<title>', close: '</title>' },
    { label: 'meta desc', open: '<meta name="description" content="">', close: '' },
    { label: 'link canon', open: '<link rel="canonical" href="">', close: '' },
    { label: 'body', open: '<body>\n', close: '\n</body>' },
    { label: 'header', open: '<header>\n', close: '\n</header>' },
    { label: 'nav', open: '<nav>\n', close: '\n</nav>' },
    { label: 'main', open: '<main>\n', close: '\n</main>' },
    { label: 'article', open: '<article>\n', close: '\n</article>' },
    { label: 'section', open: '<section>\n', close: '\n</section>' },
    { label: 'h1', open: '<h1>', close: '</h1>' },
    { label: 'h2', open: '<h2>', close: '</h2>' },
    { label: 'h3', open: '<h3>', close: '</h3>' },
    { label: 'p', open: '<p>', close: '</p>' },
    { label: 'strong', open: '<strong>', close: '</strong>' },
    { label: 'em', open: '<em>', close: '</em>' },
    { label: 'ul', open: '<ul>\n  ', close: '\n</ul>' },
    { label: 'ol', open: '<ol>\n  ', close: '\n</ol>' },
    { label: 'li', open: '<li>', close: '</li>' },
    { label: 'img', open: '<img src="" alt="">', close: '' },
    { label: 'figure', open: '<figure>\n  ', close: '\n</figure>' },
    { label: 'figcaption', open: '<figcaption>', close: '</figcaption>' },
    { label: 'a', open: '<a href="">', close: '</a>' },
    { label: 'table', open: '<table>\n  <tr>\n    <td></td>\n  </tr>\n</table>', close: '' },
    { label: 'blockquote', open: '<blockquote>\n  ', close: '\n</blockquote>' },
    { label: 'details', open: '<details>\n  <summary>Title</summary>\n  ', close: '\n</details>' },
    { label: 'time', open: '<time datetime="">', close: '</time>' },
    { label: 'footer', open: '<footer>\n', close: '\n</footer>' },
  ];